name: cameye
description: "A new Flutter project."
#
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_verification_code: ^1.1.7
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2 # Added image_cropper dependency
  permission_handler: ^11.3.1
  firebase_storage: ^12.2.0
  camera: ^0.11.0+2
  country_code_picker: ^3.0.0
  email_otp: ^3.0.2
  flutter_spinkit: ^5.2.1
  email_validator: ^3.0.0
  email_auth: ^2.0.0
  firebase_messaging: ^15.1.0
  timeago: ^3.7.0
  web_socket_channel: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

